SELECT CONCAT('SELECT * FROM ', TABLE_NAME) FROM INFORMATION_SCHEMA.TABLES
SELECT * FROM [User]
SELECT * FROM VehicleMakes
SELECT * FROM Vehicles
SELECT * FROM Location
SELECT * FROM Request
SELECT * FROM PaymentMethod
SELECT * FROM PaymentStatus
SELECT * FROM Payment
SELECT * FROM Trip
SELECT * FROM uber_data_final